version: '3.0'
services:
  redis:
    image: redis:6.2.2-alpine
    container_name: redis
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "password"]
    hostname: redis
    ports:
      - 6179:6379
    volumes:
      - ./redis-data:/data
